# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [ master, devel ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Update
      run: |
        sudo apt update
    - name: Install qgis
      run: |
        sudo apt install -yq qgis python3.10-venv
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install --upgrade flake8 pytest
        pip install --upgrade -r requriements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        python3 -m flake8 plugin/deep_segmentation_framework/ --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        python3 -m flake8 plugin/deep_segmentation_framework/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        export PYTHONPATH="/usr/lib/python3/dist-packages":PYTHONPATH && echo "import qgis" | python3
        export PYTHONPATH="$PYTHONPATH:$(pwd)/plugin"
        # we need 'xvfb-run' to simulate UI - otherwise qgis crushes
        xvfb-run python3 -m pytest plugin/deep_segmentation_framework/
